backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Création {{collection}} «{{slug}}»"
    update: "Mise à jour {{collection}} «{{slug}}»"
    delete: "Suppression {{collection}} «{{slug}}»"
    uploadMedia: "Upload de média «{{path}}»"
    deleteMedia: "Suppression de média «{{path}}»"

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "actualites"
    label: "Actualités"
    folder: "content/actualites"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Contenu", name: "body", widget: "markdown" }