backend:
  name: github
  repo: Ronyn29/montataire-basket
  branch: main
  auth_scope: repo
  base_url: https://montatairebasketball.netlify.app
  auth_endpoint: /api/auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

display_url: https://montatairebasketball.netlify.app
show_preview_links: false

collections:
  - name: "actualites"
    label: "Actualités"
    folder: "data/actualites"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "titre", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "entrainements"
    label: "Planning Entraînements"
    files:
      - label: "Planning principal"
        name: "planning_data"
        file: "data/planning.json"
        fields:
          - label: "Entraînements"
            name: "entries"
            widget: "list"
            fields:
              - { label: "Équipe", name: "equipe", widget: "string" }
              - { label: "Jour", name: "jour", widget: "string" }
              - { label: "Horaire", name: "horaire", widget: "string" }
              - { label: "Lieu", name: "lieu", widget: "string" }
