
backend:
  name: git-gateway
  branch: main
  login: true
  repo: Ronyn29/montataire-basket
  site_domain: montatairebasketball.netlify.app
  identity_url: https://montatairebasketball.netlify.app/.netlify/identity

display_url: https://montatairebasketball.netlify.app
show_preview_links: false

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "actualites"
    label: "Actualités"
    folder: "data/actualites"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "titre", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "planning"
    label: "Planning Entraînements"
    files:
      - label: "Planning principal"
        name: "planning"
        file: "data/planning.json"
        fields:
          - label: "Entraînements"
            name: "entraienements"
            widget: "list"
            fields:
              - { label: "Équipe", name: "equipe", widget: "string" }
              - { label: "Jour", name: "jour", widget: "string" }
              - { label: "Horaire", name: "horaire", widget: "string" }
              - { label: "Lieu", name: "lieu", widget: "string" }
